### ISSUE TITLE
How to change PHP settings

### ISSUE THREAD

**Issue by ipetrov87** [urbantrout/craftcms#8]
I want to set **max_input_vars = 2000**. 

I make a php.ini file and make a volume in docker-compose. 

```
craft:
    image: urbantrout/craftcms:mysql # Use mysql instead of postgresql
    depends_on:
      - mariadb
    volumes:
      - ./web/assets:/var/www/html/web/assets:z
      - ./storage/backups:/var/www/html/storage/backups # Used for db restore on start.
      - ./templates:/var/www/html/templates # Craft CMS template files
      # - ./translations:/var/www/html/translations
      - ./config/redactor:/var/www/html/config/redactor
      - ./config/general.php:/var/www/html/config/general.php
      - ./config/imager.php:/var/www/html/config/imager.php
      - ./composer.json:/var/www/html/composer.json
      -./php.ini /usr/local/etc/php/
```

But it dos`n work ;(
